### ISSUE TITLE
Rust Workshop

### ISSUE THREAD

**Issue by dtsbourg** [HackEPFL/events#6]
**Date:** Wed 12th Nov, 6PM
**Location:** BC 420, 81 seats

**TODO**
- [x] Update the poster (@dtsbourg)
- [x] Print the poster (@dtsbourg)
- [x] Put it everywhere
- [x] Ask @crackofdusk if he's willing to advertise it on Meetup?
- [x] Send e-mail to newsletter (@romac)
- [x] Put the event on techup.ch ? (@FredericJacobs)
- [x] Create Facebook event (@dtsbourg)
- [x] Twitter blast (@FredericJacobs)
- [x] Contact events.epfl.ch (@pirroh)

**Comment by dtsbourg** [comment]
Seeing as the number of answers to this issue are overwhelming, I am going to make it easier for all of us :) We will do the workshop on Thu 6th November. If anyone has a problem with that date, speak up, otherwise too bad ...

@pirroh Can I put you in charge of contacting the dean, seeing as your are a "legend at EPFL" you must have preferential treatment ;) I was thinking the same room as randomness in crypto ?

@romac Still up for the task of presenting Rust ? I will start looking for some challenges we can submit to them after the talking.

@all : Should we find a sponsor for drinks afterwards ?

**Comment by romac** [comment]
Thu 6th November sounds good!

Sure, currently toying with different kind of small programs to demo. Not sure if I'll do slides yet, or if I'll stick with code.

Having drinks afterwards would be neat indeed!

**Comment by romac** [comment]
Talked with @crackofdusk this weekend about the workshop. It happens that the 2nd Rust Romandie meetup is scheduled for the 4th, and we both think that the two events are a bit too close (even though the potential attendees shouldn't overlap too much).

Should we move the workshop earlier/later, he'd be willing to co-host the talk with me, which would be great :)

So, what do you think, should we move it? If yes, when? November 12th/13th would work for me, what about you guys + @crackofdusk?

**Comment by crackofdusk** [comment]
Nov 12/13 is okay for me. It would give us enough time to prepare.

**Comment by dtsbourg** [comment]
Sounds fine to me ! 
@romac can you tr the mails to @crackofdusk, so you can participate in the thread ?

**Comment by romac** [comment]
@dtsbourg: Done.

**Comment by pirroh** [comment]
Just reserved BC 420 for Nov 12th, 6PM.
The room sits 81 officially, plus extra chairs on the stairs and around the projector -- should be more than enough. Compared to BC01 there are no big desks between the rows, so it's way more "intimate" -- IMHO better for a workshop.

**Comment by romac** [comment]
Wonderful, thank you :)

**Comment by FredericJacobs** [comment]
Go propaganda now, go!

**Comment by crackofdusk** [comment]
Looking at the TODO:
- I'd be willing to advertise the event on Meetup starting Wednesday. I don't want to post it before tomorrow night's meetup.
- posting on techup.ch is a good idea even if it attracts one or two people. I've often found events on techup.ch that I couldn't have known about from social media.

**Comment by dtsbourg** [comment]
Poster updates are under way, will send out new version tomorrow. @pirroh can we bug you to contact events.epfl.ch to have it posted, or at the very least on the IC website under events, I know you're friendly with them. I can get you a landscape version of the poster as well if you can get us on the screens.

I'm currently writing the post for the Facebook event, I'll wait for ~9PM to post it, a more "social-media friendly time". 

Also, have we decided on a format ? Meaning is this a presentation talk, a live coding demo, are we still going to try and propose some programming challenges afterwards ? Just trying to be clear in the event description ...

**Comment by dtsbourg** [comment]
Event description, draft 1 : (I'm sure you'll want to change some things around, add or remove info. Feel free to do so before we post :) )

```
Save the date everyone ! We are starting a new series of events : workshops.

The idea is to discover new elements of programming and computer science, but also allowing you to get some practical knowledge whilst learning. This will allow for novice and expert programmers to follow along in harmony ! 

This first edition is dedicated to a language called Rust. For those of you unfamiliar with it, Rust is designed to be a "safe, concurrent, practical language", and has been developed by the Mozilla Research Team. If you're interested in learning more about it before the event, you can try some of these links :

* http://www.rust-lang.org/
* https://github.com/rust-lang/rust
* https://github.com/servo/servo

You are welcome to meet fellow enthusiasts after the workshop at Sat' for a nice cold beer ! 
```

**Comment by romac** [comment]
> Save the date everyone! We are starting a new series of events: **workshops**.
> 
> The idea is to discover new elements of programming and computer science, but also allowing you to get some practical knowledge whilst learning. This will allow for novice and expert programmers to follow along in harmony! 
> 
> This first edition is dedicated to a language called **Rust**.
> Rust is designed with memory safety, concurrency and practicality in mind, and has been developed by the Mozilla Research Team. If you're interested in learning more about it before the event, you can try some of these links:
> - http://www.rust-lang.org
> - http://doc.rust-lang.org/guide.html
> - http://rustbyexample.com
> - http://doc.crates.io
> 
> You are welcome to meet fellow enthusiasts after the workshop at Sat' for a nice cold beer!

**Comment by romac** [comment]
Haven't settled yet on a format, I'll discuss it with @crackofdusk tomorrow, and we can then update the event.
I think we'll dive straight into the code, and was thinking that, after we're done, we could let people 30min or so to write a simple Rust program of their choice, post it to gist.github.com, and then discuss the code together on the beamer, if they're up to it of course. As @crackofdusk and I have some (very shallow, for my part) experience with Rust, we should be able to help people overcome some issues they might encounter when writing those programs.

What do you think?

**Comment by romac** [comment]
@crackofdusk 
- Awesome, thanks :)
- Agreed.

**Comment by crackofdusk** [comment]
I thought about the format a bit. I propose the following:

First a short talk/live coding demo:
- Installing a nightly build
- Intro to Cargo (starting a new project, declaring dependencies)
- Rudimentary intro to enums, structs, traits

Then, in groups of 2 we start making a simple chat . This involves:
- Spawning tasks
- Message passing via channels
- Probably mutexes
- Refactoring into modules
- Later: sockets, nicks list and any features people want to implement if they have time

I think we can easily iterate. Writing a real program will teach people to read the docs and guides and after each step we can review together/have a different group present their solution. Also, in the end, maybe some of the participants will have written a complete program that compiles and works. It's nice to have that first program you wrote with some help that you can refer to when you return to Rust.

**Comment by dtsbourg** [comment]
@crackofdusk That seems perfect ! We can discuss it more tomorrow, I'll be coming to the meetup as well.

**Comment by romac** [comment]
@crackofdusk That sounds like the perfect workshop indeed :) Yeah, let's discuss all that at the meetup tomorrow. Looking forward to hearing about FFI, unsafe, etc. btw :)

**Comment by romac** [comment]
I'm gonna wait until Wednesday before putting the event on techup.ch, and post to the newsletter as not to confuse people since there's already a meetup tomorrow.

**Comment by FredericJacobs** [comment]
Hey,
I put it up on techup and will regularly tweet about it.
Also invited some folks on Facebook and sent it to some groups that might be interested.

Can someone post it to events.epfl.ch and to our mailing list?

Thanks.

**Comment by romac** [comment]
Great, thanks! I'll take care of the mailing list.

---

**Comment by dtsbourg** [comment]
Posters are printed ! I made a first batch of 20 A3, that should get us started. We can always print more on Monday in case they decide to clean up the posters this week-end.
Anybody want to spend half an hour walking around and pasting paper to walls with me ? :D

**Comment by romac** [comment]
Newsletter sent!

**Comment by FredericJacobs** [comment]
Hey,
I've been thinking and I'm happy to present something about memory safety. Should be around 10 minutes. Based on an example of exploitable bugs.

**Comment by antoinealb** [comment]
Hello,
Don't know if it is the correct place to post about it. The talk was very interesting, thanks a lot for preparing that, but I think next time it would be better to use the PA (sound) system of the room. It would make the talk much more comfortable, both for the audience and for the speakers.

Also from a content point of view, maybe less time on the syntax and more about the type of bugs Rust could prevent would have been better IMHO (maybe with examples in C and rust).

**Comment by FredericJacobs** [comment]
Thanks for the feedback!

**Comment by romac** [comment]
@antoinealb Thanks for the feedback! I agree with both of your points.

If I had to redo the talk, I would have halved the number of slides and focuses solely on memory safety and concurrency. We spent a lot of time on syntax and other features as we initially had in mind to have a workshop right after the talk and wanted to give people a good overview of the language so they could start writing code right away. Not something we'll attempt again I think.
